on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: '{"clientId":"${{ secrets.REGISTRY_USERNAME }}","clientSecret":"${{ secrets.REGISTRY_PASSWORD }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f deployment/Dockerfile-minimal -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/databricks-dcs-minimal-demo:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/databricks-dcs-minimal-demo:latest
            docker build -f deployment/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/databricks-dcs-demo:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/databricks-dcs-demo:latest
